# Generated by Django 2.0.3 on 2018-03-10 23:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('party', models.TextField(blank=True, null=True)),
                ('ico', models.TextField(blank=True, null=True)),
                ('status', models.TextField(blank=True, null=True)),
                ('office', models.TextField(blank=True, null=True)),
                ('district', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Committee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
                ('type', models.TextField(blank=True, null=True)),
                ('party', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('city', models.TextField(blank=True, null=True)),
                ('state', models.TextField(blank=True, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=9, null=True)),
                ('employer', models.TextField(blank=True, null=True)),
                ('occupation', models.TextField(blank=True, null=True)),
                ('organization', models.TextField(blank=True, null=True)),
                ('industry', models.TextField(blank=True, null=True)),
                ('entity_type', models.TextField(blank=True, null=True)),
                ('committee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='election_data.Committee')),
            ],
        ),
        migrations.CreateModel(
            name='ElectionResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('single_county_race_id', models.TextField(blank=True, null=True)),
                ('mult_county_race_id', models.TextField(blank=True, null=True)),
                ('mult_county_candidate_id', models.TextField(blank=True, null=True)),
                ('is_multiple_county_race', models.NullBooleanField()),
                ('county_name', models.TextField(blank=True, null=True)),
                ('jurisdiction_code', models.TextField(blank=True, null=True)),
                ('jurisdiction_code_description', models.TextField(blank=True, null=True)),
                ('election_year', models.IntegerField(blank=True, null=True)),
                ('election_date', models.DateField(blank=True, null=True)),
                ('political_jurisdiction', models.TextField(blank=True, null=True)),
                ('is_csd', models.NullBooleanField()),
                ('office', models.TextField(blank=True, null=True)),
                ('office_code', models.TextField(blank=True, null=True)),
                ('office_code_description', models.TextField(blank=True, null=True)),
                ('area_within_office', models.TextField(blank=True, null=True)),
                ('term_of_office', models.TextField(blank=True, null=True)),
                ('number_seats_to_be_filled', models.IntegerField(blank=True, null=True)),
                ('candidate_ballot_designation', models.TextField(blank=True, null=True)),
                ('is_incumbent', models.NullBooleanField()),
                ('number_candidates_running', models.IntegerField(blank=True, null=True)),
                ('number_votes_for_candidate', models.IntegerField(blank=True, null=True)),
                ('total_votes_for_all_candidates', models.IntegerField(blank=True, null=True)),
                ('rank_order_of_candidates', models.IntegerField(blank=True, null=True)),
                ('percent_votes_received_by_candidate', models.DecimalField(decimal_places=6, max_digits=15)),
                ('candidate_election_outcome', models.IntegerField(blank=True, null=True)),
                ('candidate_election_outcome_description', models.TextField(blank=True, null=True)),
                ('mult_county_number_votes_for_candidate', models.IntegerField(blank=True, null=True)),
                ('mult_county_total_votes_for_all_candidates', models.IntegerField(blank=True, null=True)),
                ('mult_county_rank_order_of_candidates', models.IntegerField(blank=True, null=True)),
                ('mult_county_candidate_election_outcome', models.IntegerField(blank=True, null=True)),
                ('mult_county_candidate_election_outcome_description', models.TextField(blank=True, null=True)),
                ('candidate_last_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='election_data.Candidate')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.TextField(blank=True, null=True)),
                ('election_cycle', models.TextField(blank=True, null=True)),
                ('election', models.DateField(blank=True, null=True)),
                ('primary_general_indicator', models.IntegerField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('transaction_amount', models.DecimalField(decimal_places=6, max_digits=15)),
                ('filed_date', models.DateField(blank=True, null=True)),
                ('recipient_committee_name', models.TextField(blank=True, null=True)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='election_data.Donor')),
                ('recipient_candidate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='election_data.Candidate')),
            ],
        ),
    ]
