"""
Django settings for congressionaldata project.

Generated by 'django-admin startproject' using Django 2.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""

from congressionaldata.settings import common
import os
import urllib.parse

# Read DB URI From Environment Variable
CD_DWH = os.getenv('CD_DWH')

PARSED_DBURI = urllib.parse.urlparse(CD_DWH)

ALLOWED_HOSTS = []
CORS_ORIGIN_WHITELIST = ('localhost:8080','127.0.0.1:8080')

DEBUG = False

# Database
# https://docs.djangoproject.com/en/2.0/ref/settings/#databases

DATABASES = {
    # Slack the #datasci-congressdata group for the appropriate credential
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': PARSED_DBURI.path[1:],
        'USER': PARSED_DBURI.username,
        'PASSWORD': PARSED_DBURI.password,
        'HOST': PARSED_DBURI.hostname,
        'PORT': '5432',
        'OPTIONS': {
            'options': '-c search_path=stg_analytics,trg_analytics',
            'sslmode': 'require',
        }
    }
}

try:
    from secrets import local_settings
except ImportError:
    pass
